[package]
name = "crossbuild-wrappers"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Compiler wrapper generation for cross-compilation toolchains"
keywords.workspace = true
categories.workspace = true

[dependencies]
crossbuild-core = { path = "../core", version = "1.0.0" }