[package]
name = "crossbuild-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbuild-core = { path = "../core" }
crossbuild-cache = { path = "../cache" }
crossbuild-downloader = { path = "../downloader" }
crossbuild-installer = { path = "../installer" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }