[package]
name = "crossbuild-provider-clang"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Clang/LLVM toolchain provider for cross-compilation"
keywords.workspace = true
categories.workspace = true

[dependencies]
crossbuild-core = { path = "../../core" }
anyhow = { workspace = true }
which = { workspace = true }