use std::path::{Path, PathBuf};

use crossbuild_core::{
    model::TargetTriple,
    provider::LinkerFlavor,
    error::CrossBuildError,
};

/// Wrapper command configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrapperConfig {
    pub wrapper: String,
    pub target: String,
    pub flavor: LinkerFlavor,
}

impl WrapperConfig {
    pub fn new(wrapper: impl Into<String>, target: impl Into<String>) -> Self {
        Self {
            wrapper: wrapper.into(),
            target: target.into(),
            flavor: LinkerFlavor::Gnu,
        }
    }

    pub fn with_flavor(mut self, flavor: LinkerFlavor) -> Self {
        self.flavor = flavor;
        self
    }
}

/// Generates wrapper scripts for cross-compilation.
pub struct WrapperGenerator {
    target: TargetTriple,
    toolchain_path: Option<PathBuf>,
    sysroot: Option<PathBuf>,
    wrappers: Vec<WrapperConfig>,
}

impl WrapperGenerator {
    pub fn new(target: TargetTriple) -> Self {
        Self {
            target,
            toolchain_path: None,
            sysroot: None,
            wrappers: Vec::new(),
        }
    }

    pub fn with_toolchain_path(mut self, path: PathBuf) -> Self {
        self.toolchain_path = Some(path);
        self
    }

    pub fn with_sysroot(mut self, path: PathBuf) -> Self {
        self.sysroot = Some(path);
        self
    }

    pub fn add_wrapper(mut self, config: WrapperConfig) -> Self {
        self.wrappers.push(config);
        self
    }

    /// Generates all wrapper scripts.
    pub fn generate(&self, output_dir: &Path) -> Result<Vec<PathBuf>, CrossBuildError> {
        std::fs::create_dir_all(output_dir).map_err(|e| CrossBuildError::Io {
            path: Some(output_dir.to_path_buf()),
            source: e,
        })?;

        let mut generated = Vec::new();

        // Generate standard wrappers
        let target_str = self.target.triple.clone();
        let wrappers = [
            ("cc", target_str.as_str(), LinkerFlavor::Gnu),
            ("c++", target_str.as_str(), LinkerFlavor::Gnu),
            ("ar", "", LinkerFlavor::Gnu),
            ("ld", "", LinkerFlavor::Gnu),
            ("ranlib", "", LinkerFlavor::Gnu),
            ("strip", "", LinkerFlavor::Gnu),
            ("objcopy", "", LinkerFlavor::Gnu),
            ("objdump", "", LinkerFlavor::Gnu),
            ("nm", "", LinkerFlavor::Gnu),
            ("size", "", LinkerFlavor::Gnu),
            ("strings", "", LinkerFlavor::Gnu),
        ];

        for (name, target_arg, flavor) in wrappers {
            let wrapper_path = output_dir.join(name);
            let script = self.generate_wrapper_script(name, target_arg, flavor)?;
            std::fs::write(&wrapper_path, script).map_err(|e| CrossBuildError::Io {
                path: Some(wrapper_path.clone()),
                source: e,
            })?;
            generated.push(wrapper_path);
        }

        Ok(generated)
    }

    fn generate_wrapper_script(
        &self,
        name: &str,
        target_arg: &str,
        _flavor: LinkerFlavor,
    ) -> Result<String, CrossBuildError> {
        let mut script = String::new();

        script.push_str("#!/bin/sh\n");
        script.push_str("# Generated by cargo-crossbuild\n\n");

        // Set up environment
        script.push_str("# Set up cross-compilation environment\n");
        script.push_str(&format!("export TARGET={}\n", self.target.triple));

        if let Some(sysroot) = &self.sysroot {
            script.push_str(&format!("export SYSROOT={}\n", sysroot.display()));
        }

        if let Some(toolchain) = &self.toolchain_path {
            script.push_str(&format!("export TOOLCHAIN_PATH={}\n", toolchain.display()));
        }

        // Build the command
        match name {
            "cc" | "c++" => {
                if !target_arg.is_empty() {
                    script.push_str(&format!("\nexec {} -target {} \"$@\"\n", name, target_arg));
                } else {
                    script.push_str(&format!("\nexec {} \"$@\"\n", name));
                }
            }
            "ar" => {
                script.push_str("\nexec ar \"$@\"\n");
            }
            "ld" => {
                script.push_str(&format!("\nexec ld.lld \"$@\"\n"));
            }
            _ => {
                script.push_str(&format!("\nexec {} \"$@\"\n", name));
            }
        }

        Ok(script)
    }

    /// Installs wrappers to a directory in PATH.
    pub fn install_to_path(&self, bin_dir: &Path) -> Result<Vec<PathBuf>, CrossBuildError> {
        let wrappers = self.generate(bin_dir)?;
        Ok(wrappers)
    }
}

/// Standard wrapper configurations.
pub fn standard_wrappers(target: TargetTriple) -> Vec<WrapperConfig> {
    vec![
        WrapperConfig::new("crossbuild-cc", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
        WrapperConfig::new("crossbuild-c++", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
        WrapperConfig::new("crossbuild-ar", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
        WrapperConfig::new("crossbuild-ld", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
        WrapperConfig::new("crossbuild-ranlib", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
        WrapperConfig::new("crossbuild-strip", target.to_string())
            .with_flavor(LinkerFlavor::Gnu),
    ]
}

/// Creates a runner wrapper for the target.
pub fn create_runner_wrapper(
    target: &TargetTriple,
    _toolchain_path: Option<PathBuf>,
) -> Result<String, CrossBuildError> {
    let mut script = String::new();

    script.push_str("#!/bin/sh\n");
    script.push_str("# Generated runner for cross-execution\n\n");

    if target.is_wasm() {
        script.push_str("# WebAssembly runner\n");
        script.push_str("exec wasmtime \"$@\"\n");
    } else if target.is_linux() {
        script.push_str("# Linux runner (uses qemu-user)\n");
        script.push_str("exec qemu-x86_64 \"$@\"\n");
    } else if target.is_windows() {
        script.push_str("# Windows runner (uses wine)\n");
        script.push_str("exec wine \"$@\"\n");
    } else {
        script.push_str("# Generic runner\n");
        script.push_str("exec \"$@\"\n");
    }

    Ok(script)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crossbuild_core::model::TargetTriple;

    #[test]
    fn generates_cc_wrapper() {
        let target = TargetTriple::parse("x86_64-unknown-linux-gnu").unwrap();
        let generator = WrapperGenerator::new(target)
            .with_toolchain_path("/opt/rust".into())
            .with_sysroot("/opt/sysroot".into());

        let script = generator.generate_wrapper_script("cc", "x86_64-unknown-linux-gnu", LinkerFlavor::Gnu).unwrap();
        assert!(script.contains("TARGET="));
        assert!(script.contains("SYSROOT="));
        assert!(script.contains("exec cc -target"));
    }

    #[test]
    fn generates_ar_wrapper() {
        let target = TargetTriple::parse("x86_64-unknown-linux-gnu").unwrap();
        let generator = WrapperGenerator::new(target);
        let script = generator.generate_wrapper_script("ar", "", LinkerFlavor::Gnu).unwrap();
        assert!(script.contains("exec ar"));
    }

    #[test]
    fn creates_runner_wrapper() {
        let target = crossbuild_core::model::TargetTriple::parse("wasm32-wasi").unwrap();
        let script = create_runner_wrapper(&target, None).unwrap();
        assert!(script.contains("wasmtime"));
    }
}