[package]
name = "crossbuild-installer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Installation and extraction of toolchain artifacts"
keywords.workspace = true
categories.workspace = true

[dependencies]
crossbuild-core = { path = "../core", version = "1.0.0" }
crossbuild-cache = { path = "../cache", version = "1.0.0" }
crossbuild-downloader = { path = "../downloader", version = "1.0.0" }
anyhow = { workspace = true }
fs_extra = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }