[package]
name = "crossbuild-provider-zig"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Zig toolchain provider leveraging zig cc as a cross-compiler"
keywords.workspace = true
categories.workspace = true

[dependencies]
crossbuild-core = { path = "../../core", version = "1.0.0" }
anyhow = { workspace = true }
which = { workspace = true }