[package]
name = "crossbuild-environment"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbuild-core = { path = "../core" }
crossbuild-toolchain = { path = "../toolchain" }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }