[package]
name = "crossbuild-provider-gcc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "GCC toolchain provider for cross-compilation"
keywords.workspace = true
categories.workspace = true

[dependencies]
crossbuild-core = { path = "../../core", version = "1.0.0" }
anyhow = { workspace = true }
which = { workspace = true }